### ISSUE TITLE
All file object attributes being sent along with actual xhr

### ISSUE THREAD

**Issue by daniel-ferguson** [homeslicesolutions/backbone-model-file-upload#12]
Hey, I've done a pretty minimal setup, with a single file attached to a model instance. It seems like there's a little bit of overhead going on in the upload xhr. Due to the flattening of attributes, I seem to end up with something like this being sent to the rails server.
The `#<ActionDispatch::Http>` stuff is just rails interpreting the raw bytes as a file (the bit that I want):

```
img.webkitRelativePath: "" 
img.lastModified: "1417019673000"
img.name: "Screenshot from 2014-11-26 16:34:33.png"
img.type: "image/png"
img.size: "33715"

img: #<ActionDispatch::Http::UploadedFile:0x007ffd68d50918 @tempfile=#<Tempfile:/tmp/RackMultipart20141212-8277-1uyxe66>, @original_filename="Screenshot from 2014-11-26 16:34:33.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"img\"; filename=\"Screenshot from 2014-11-26 16:34:33.png\"\r\nContent-Type: image/png\r\n">
```

The other attributes I'm just throwing away. I'll have a dig in and see if I can patch it up for my use case to not send file attributes, but was wondering if you want those attributes being sent or if it's just a side effect of accounting for nested objects in other attributes of the backbone model.

Cheers for a lovely plugin btw, perfect for my current use case.

**Comment by eat-multi** [comment]
Sounds like a cool idea.
I've heard images can end up being some 30% bigger MB-wise in base64 (which json can transmit), but that may well be worth it simplicity wise, decoding it server side should be no problem.

The issue with flattening is that different web frameworks tend towards different defaults for how things should be flattened, rails uses ```object[field]``` notation in forms.

Anyway, just food for thought.
Thanks for writing this, found it very useful, I made some project-specific changes and all is good :)

**Comment by homeslicesolutions** [comment]
Actually I think i take it back since doing it all in a JSON post it won't "stream" but try to push the string all at once.  So no POST JSON, we need to use the FormData API.

**Comment by eat-multi** [comment]
Ah, didn't think of that.
