### ISSUE TITLE
'Maximum callstack exceeded' when saving with nested attributes

### ISSUE THREAD

**Issue by jbhatab** [homeslicesolutions/backbone-model-file-upload#14]
I'm having an issue similar to a previous issue posted, https://github.com/homeslicesolutions/backbone-model-file-upload/issues/2.

I'm using backbone nested attributes, https://github.com/dtmtec/backbone-nested-attributes, to save my backbone models correctly with my rails backend. The problem is that when I try and save a photo on a model with any relationships, it gives me the error 'maximum callstack exceeded'. 

I did get the photo saving to work if I disabled a part of the flatten function, but it broke the nested part of my code. Any ideas?

Here's how I changed the flatten function.

```
  _flatten: function( obj ) {
      var output = {};
      for (var i in obj) {
        if (!obj.hasOwnProperty(i)) continue;
        // I commented this out and made it false instead
        // it at least makes the photo uploading work.
        //if (typeof obj[i] == 'object') {
        if (false) {
          var flatObject = this._flatten(obj[i]);
          for (var x in flatObject) {
            if (!flatObject.hasOwnProperty(x)) continue;
            output[i + '.' + x] = flatObject[x];
          }
        } else {
          output[i] = obj[i];
        }
      }
      return output;
```

**Comment by dlevacher** [comment]
I got the problem, added this code at the beginning of the `_flatten` function

`if (obj instanceof Backbone.Model || obj instanceof Backbone.Collection) 
        obj = obj.toJSON();
` 

as suggested from this fix of backbone nested validate https://github.com/thedersen/backbone.validation/pull/97

It did the trick, no more recursive error.

**Comment by homeslicesolutions** [comment]
I'm seeing this more and more nowadays that people are nesting Backbone elements into their models and collections.  It's a really strange thing to me and I'm unsure if this is good practice as I've talked with my co-workers here.  Anyways... I'm unsure if I'm going to accept this pull request since I'm against this pattern, so maybe I would suggest for you to fork your own on this.

**Comment by jbhatab** [comment]
So I found out that I was doing hacky stuff to get it to work with rails, but this fixed everything. I changed the flatten function slightly so that it surrounds the data in brackets instead of using dot notation. With my rails backend this worked great and allowed me to still use nested attributes and keep the whole flatten function working for photos.

```
    _flatten: function( obj ) {
      var output = {};
      for (var i in obj) {
        if (!obj.hasOwnProperty(i)) continue;
        if (typeof obj[i] == 'object') {
          var flatObject = this._flatten(obj[i]);
          for (var x in flatObject) {
            if (!flatObject.hasOwnProperty(x)) continue;
            output[i + '[' + x +']'] = flatObject[x];
          }
        } else {
          output[i] = obj[i];
        }
      }
      return output;

    },
```
