### ISSUE TITLE
Node qs body parse convention

### ISSUE THREAD

**Issue by DanilloCorvalan** [homeslicesolutions/backbone-model-file-upload#17]
For people who are experience problems with body parsing arrays for example, this library uses a different convention for dealing with arrays. `arrayProperty.index.property` which is not accepted by body-parser library for nodejs + express.

The common format is to cover them with square braces such as `arrayProperty[index][property]`. In order to do that I had to change **line 128**:

- old version: `output[i + '.' + x] = flatObject[x];`
- new version: `output['[' + i + '][' + x + ']'] = flatObject[x];`

I didn't submit a pull request because I don't know whether this is particular for people who works with nodejs and express body parser.

**Comment by homeslicesolutions** [comment]
You're the second one to suggest this.  I'm thinking we should do the bracket.  Feel free to do the PR.  I think we need to change it.  

I used the dot notation cause I expected it to be a simple delimiter (see my node test server), but brackets seem to solve many issues even in the ruby world. 

Thanks!  Looking forward to the PR.

**Comment by homeslicesolutions** [comment]
So changed that notation up a bit.  So it looks more like this now:

`output['something[nested[inside]]'] = true`

I was able to parse this quite easily and I included an "unflatten" method in the class.  You can use that as a guide to how you would parse the flattened model in other languages
