### ISSUE TITLE
Tag the v1.0.0

### ISSUE THREAD

**Issue by benatespina** [homeslicesolutions/backbone-model-file-upload#22]
Hi, you have a commit that says "version 1.0.0". Can you tag this release to avoid this?
```
"backbone-model-file-upload": "*",
```

**Comment by homeslicesolutions** [comment]
Sorry i'm not familiar on what i need to do.  So i just need to change the package.json?  or do i need to re-tag the git repo then push it back?

**Comment by benatespina** [comment]
@homeslicesolutions sorry, what I say is that your library doesn't have any tag yet. So that we can use in production safely we need stable release :)

https://github.com/homeslicesolutions/backbone-model-file-upload/releases

**Comment by benatespina** [comment]
@homeslicesolutions Thanks man!! ;)
