### ISSUE TITLE
Recursive _flatten

### ISSUE THREAD

**Issue by lutherism** [homeslicesolutions/backbone-model-file-upload#3]
If a model references itself, the _flatten() function goes recursive on save.

Ideally, _flatten() should check for instance of self, and ignore it.

**Comment by dlevacher** [comment]
I got the problem, added this code at the beginning of the `_flatten` function

`if (obj instanceof Backbone.Model || obj instanceof Backbone.Collection) 
        obj = obj.toJSON();
` 

as suggested from this fix of backbone nested validate https://github.com/thedersen/backbone.validation/pull/97

It did the trick, no more recursive error.
