### ISSUE TITLE
Update the version

### ISSUE THREAD

**Issue by brenfrow** [homeslicesolutions/backbone-model-file-upload#30]
When using this plugin I noticed phantomjs started being installed on my production deploys. Looking further I found the phantomjs amongst the grunt-contrib-jasmine dependency. It looks like when installing with npm version 1.0.0 it grabs SHA 53b98cd4bf71d5082dcb0d574e21d2dd29fd28f3 where the dev dependencies are in the the dependencies. I think updating the version # will probably fix this.

**Comment by homeslicesolutions** [comment]
Oh the dependencies are only needed if you want to test and develop the plugin.  You don't need to run npm install to use the plugin.

Joe

**Comment by brenfrow** [comment]
What i mean is when you include it in your package as a dependency and install. It pulls in all the devdependencies

**Comment by homeslicesolutions** [comment]
I gotcha. I can tag a new version, but to my knowledge I"m not sure if this will solve your issue.  I think you need to run "npm prune" to get rid of dependencies that aren't required in the newest setup of my plugin.

**Comment by MerlinBB** [comment]
Thanks for the plugin, finding it really useful :)

I think a new release is required as the commit you made moving the build/testing stuff to dev dependencies (https://github.com/homeslicesolutions/backbone-model-file-upload/commit/35f623c834b4b48a63896a70e082d97b7878a1c4) was made after the release, so npm isn't aware of it.

**Comment by homeslicesolutions** [comment]
@MerlinBB @brenfrow Sorry for the long delay.  I was confused to how this worked.   Can you try now to see if this still happens?  Please reopen if it is still down

**Comment by MerlinBB** [comment]
![image](https://cloud.githubusercontent.com/assets/3215478/18465332/2149b39c-798e-11e6-9b9d-632a5bf0e097.png)

Perfect, thanks!
