### ISSUE TITLE
PUT method doesnt send file to server

### ISSUE THREAD

**Issue by is-blackhole** [homeslicesolutions/backbone-model-file-upload#34]
Hello!

Just found small problem with file upload and existing model updates, which is sent with PUT request.

Looks like FormData with files need to passed with POST method only, PUT will send only filename and not the file body :(  And according to SO discussions its a browsers (or standarts) limitation.
Forcing m.save(null, {method: 'POST'}) will send all data, just need to check model id on server to distinguish create/update.

Hope this will help somebody in future :)

**Comment by homeslicesolutions** [comment]
Thanks for this as I will make sure that the README contains this restriction.
